{% set version = "2.9.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-distr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/distr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/distr/distr_{{ version }}.tar.gz
  sha256: 5f1d8067b9dc5fbc2cf9fe804454f512a662076db304fbd73d8fa11038abaffe

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-sfsmisc
    - r-startupmsg
  run:
    - r-base
    - r-mass
    - r-sfsmisc
    - r-startupmsg

test:
  commands:
    - $R -e "library('distr')"           # [not win]
    - "\"%R%\" -e \"library('distr')\""  # [win]

about:
  home: http://distr.r-forge.r-project.org/
  license: LGPL-3.0-only
  summary: S4-classes and methods for distributions.
  license_family: LGPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
