appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: adPlCB+sbWC6EaVGOxrdQrUpSXgTgBMnrrN+8iqxFbSyzTd1gZqGUj1wMOaiBak0D9jpm0bTbkz/Kr74Zolfnn9OY5ThoXL/d6flBMFH7pDJ7C7pt1qf5j/ZqfsWCANaPzPXlOCTwvxYqvgdYoIjho6BtDKb00SHKb2yIPptAdwTrtPu+Ge5PRHwxXBq3LWk+xt/6y/x5wP9qSafUknpcCQ5IDCCwQq95Nkc4YxlmLRDlg+468tMTxww7OH8FuXyLLDhREto0yOuHl6TiY6RMFWGMsw1QaNVrfpmg6NH9QWEgBYebs9qpASFt2dW/31Jjcm0GHKzXwY07j/rSc3tIHjbdzdN5hiSZ8gAfAy8hqX9xfPPf2QBLOtG0kzhY0lJfwtlwe7GgMuyHGTszOkPdcug7IZQ6bbE2Je4oPhWnGamqpUslV7E7aNFYsbaA09GTb816Yey0ktzYjHTLVoLrTnwLufPigTp7hhPm3No/94ymqVg1Floonu8HcdzJ++eLVlg+zwjRsSmt0ivgIplHRy7aLaFPP95PTvT4lTYnckl9FTA2VemWLXYF9ZcmLdllcxIg7wOUm+yIPvffN9BbjgqHta0/95PW39Oj1BvWj1pQ14gJrRR+77tY9WqNmzlM+5VWd0Efm/sa83CE5nEZellTslC6fMVJ6Js01km8t0=}
